/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AnimatedModel(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/AnimatedModel.glb')
  //const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, -3, -50]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01,0.01,0.01]}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Cube003">
            <skinnedMesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['necklace.002']} skeleton={nodes.Cube003_1.skeleton} />
            <skinnedMesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials.HAIR} skeleton={nodes.Cube003_2.skeleton} />
            <skinnedMesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials.SKIN} skeleton={nodes.Cube003_3.skeleton} />
            <skinnedMesh name="Cube003_4" geometry={nodes.Cube003_4.geometry} material={materials.WING} skeleton={nodes.Cube003_4.skeleton} />
            <skinnedMesh name="Cube003_5" geometry={nodes.Cube003_5.geometry} material={materials['ROBE.001']} skeleton={nodes.Cube003_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedModel.glb')
