/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { useControls } from "leva";

export function Model(props) {
  const { Model_scale, Model_position, Model_rotation } = useControls({
    Model_scale: [0.03, 0.03, 0.03],
    Model_position: [-0.20, -0.05, 0.0],
    Model_rotation: [3.10, 3.25, Math.PI * 1]
});
  const { nodes, materials } = useGLTF('/Homepage-scene.gltf')
  return (
    <mesh scale={Model_scale} position={Model_position} rotation={Model_rotation}>
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube891.geometry} material={materials.TREES} position={[0.86, 6.8, 56.75]} rotation={[-Math.PI, 0.72, -Math.PI]} />
      <mesh geometry={nodes.Cube900.geometry} material={materials.TREES} position={[16.75, 11.01, 66.53]} rotation={[0, 0.09, 0]} />
      <mesh geometry={nodes.Cube892.geometry} material={materials.TREES} position={[-14.72, 13.75, 77.22]} rotation={[0, -0.71, -0.1]} />
      <mesh geometry={nodes.Cube894.geometry} material={materials.TREES} position={[-5.4, 8.41, 48.54]} rotation={[0, -0.18, 0]} />
      <mesh geometry={nodes.Cube877.geometry} material={materials.TREES} position={[2.98, 10.88, 67.53]} rotation={[Math.PI, -0.43, Math.PI]} />
      <mesh geometry={nodes.Model.geometry} material={materials.IANUA} position={[-15.64, 7.88, 57.86]} rotation={[0, 0.09, 0]} />
      <mesh geometry={nodes.gras_plane.geometry} material={materials.GROUND} position={[2.88, -2.36, 44.02]} rotation={[-0.01, 0.04, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.TREES} position={[-16.57, 8.41, 52.48]} rotation={[Math.PI, -0.63, Math.PI]} />
    </group>
    </mesh>
  )
}

useGLTF.preload('/Homepage-scene.gltf')
