/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

import { useControls } from 'leva'

export function Model(props) {
  const Texture_Loader = new THREE.TextureLoader()
  const Model_Texture = Texture_Loader.load('/Model.png')
  Model_Texture.flipY = false
  const IANUA_Material = new THREE.MeshBasicMaterial( { map : Model_Texture } )
  const { Model_Position, Model_Rotation, Model_Scale } = useControls({
    Model_Position: [0, -0.2, 0],
    Model_Rotation: [0, -0.46, 0],
    Model_Scale: [0.1,0.1,0.1]
  })
  const { nodes } = useGLTF('/Model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.IANUA.geometry}
        material={IANUA_Material}
        position={Model_Position}
        rotation={Model_Rotation}
        scale={Model_Scale} />
    </group>
  )
}

useGLTF.preload('/Model.gltf')
