/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF('/Model.gltf')
  return (
    <group {...props} dispose={null}>
        <group position={[0,0,0]} scale={[0.3,0.3,0.3]}>
          <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.02, 121.79, -159.38]} />
          <mesh geometry={nodes.gras_plane.geometry} material={nodes.gras_plane.material} position={[0.36, 0.47, -2.22]} />
        </group>
    </group>
  )
}

useGLTF.preload('/Model.gltf')
