/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Homepage-scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.IANUA.geometry} material={nodes.IANUA.material} position={[-1.1, 9.3, 68.74]} rotation={[0, -0.23, 0]} />
      <mesh geometry={nodes.tree_006.geometry} material={nodes.tree_006.material} position={[-8.83, 4.21, 42.65]} rotation={[0, -1.14, 0]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_007_.geometry} material={nodes.tree_007_.material} position={[-7.79, 7.29, 44.01]} rotation={[Math.PI, -1.07, Math.PI]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_008.geometry} material={nodes.tree_008.material} position={[-2.94, 8.59, 47.86]} rotation={[0, -1.26, -0.1]} scale={2.2} />
      <mesh geometry={nodes.tree_010.geometry} material={nodes.tree_010.material} position={[-0.41, 5.42, 39.14]} rotation={[0, -1.26, 0]} scale={[1.74, 2.2, 2.38]} />
      <mesh geometry={nodes.tree_011.geometry} material={nodes.tree_011.material} position={[12.48, 2.82, 30.37]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_013.geometry} material={nodes.tree_013.material} position={[8.12, 3.07, 40.47]} rotation={[0, -0.59, 0]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_014.geometry} material={nodes.tree_014.material} position={[12.67, 5.79, 39.14]} rotation={[0, -1.26, 0]} scale={[1.74, 2.2, 2.38]} />
      <mesh geometry={nodes.tree_031.geometry} material={nodes.tree_031.material} position={[8.06, 4.61, 35.22]} rotation={[0, 0.89, 0]} scale={[2.05, 1.97, 2.39]} />
      <mesh geometry={nodes.tree_036.geometry} material={nodes.tree_036.material} position={[12.65, 5.84, 34.9]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_039.geometry} material={nodes.tree_039.material} position={[18.78, 4.16, 40.64]} rotation={[-Math.PI, -1.41, -Math.PI]} scale={[3.2, 2.84, 3.23]} />
      <mesh geometry={nodes.tree_040.geometry} material={nodes.tree_040.material} position={[18.44, 7.29, 44.01]} rotation={[Math.PI, -1.07, Math.PI]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_045.geometry} material={nodes.tree_045.material} position={[18.06, 2.85, 23.85]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_001.geometry} material={nodes.tree_001.material} position={[-27.08, 10.2, 46.81]} rotation={[-0.01, 1.41, -0.09]} scale={[2.55, 2.27, 2.57]} />
      <mesh geometry={nodes.tree_002.geometry} material={nodes.tree_002.material} position={[-22.45, 4.14, 23.25]} rotation={[0, 0.89, 0]} scale={[2.05, 1.97, 2.39]} />
      <mesh geometry={nodes.tree_003.geometry} material={nodes.tree_003.material} position={[-19.72, 4.73, 34.9]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_004.geometry} material={nodes.tree_004.material} position={[-22.46, 4.46, 19.02]} rotation={[-0.01, 1.41, -0.09]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_005.geometry} material={nodes.tree_005.material} position={[-41.14, -1.42, 19.08]} rotation={[-3.14, 0.92, 3.04]} scale={3.02} />
      <mesh geometry={nodes.tree_009.geometry} material={nodes.tree_009.material} position={[-3.8, 5.14, 41.75]} rotation={[0, 1.41, 0]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_012.geometry} material={nodes.tree_012.material} position={[2.95, 6.83, 23.54]} rotation={[-3.14, 0.92, 3.04]} scale={3.02} />
      <mesh geometry={nodes.tree_015.geometry} material={nodes.tree_015.material} position={[-4.64, 5.16, 25.32]} rotation={[-0.01, 1.41, -0.09]} scale={[3.05, 2.71, 3.07]} />
      <mesh geometry={nodes.tree_016.geometry} material={nodes.tree_016.material} position={[-2.67, 0.9, 14.89]} rotation={[0, 0.89, 0]} scale={[2.05, 1.97, 2.39]} />
      <mesh geometry={nodes.tree_017.geometry} material={nodes.tree_017.material} position={[-9.4, 2.85, 23.85]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_018.geometry} material={nodes.tree_018.material} position={[-4.38, 3.88, 28.74]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_019.geometry} material={nodes.tree_019.material} position={[-5.75, 3.11, 11.63]} rotation={[-0.01, 1.41, -0.09]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_020.geometry} material={nodes.tree_020.material} position={[5.94, 0.6, 29.26]} rotation={[-Math.PI, -1.41, -Math.PI]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_021.geometry} material={nodes.tree_021.material} position={[7.23, 1.17, 25.3]} rotation={[Math.PI, -1.07, Math.PI]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_022.geometry} material={nodes.tree_022.material} position={[5.62, 4.01, 35.98]} rotation={[Math.PI, -1.07, Math.PI]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_023.geometry} material={nodes.tree_023.material} position={[-28.71, -0.96, 23.77]} rotation={[0, -1.26, 0]} scale={[1.74, 2.2, 2.38]} />
      <mesh geometry={nodes.tree_024.geometry} material={nodes.tree_024.material} position={[-19.19, -0.69, 23.77]} rotation={[0, -1.26, 0]} scale={[1.74, 2.2, 2.38]} />
      <mesh geometry={nodes.tree_025.geometry} material={nodes.tree_025.material} position={[-21.73, 5.27, 35.22]} rotation={[0, 0.89, 0]} scale={[2.05, 1.97, 2.39]} />
      <mesh geometry={nodes.tree_026.geometry} material={nodes.tree_026.material} position={[-26.26, 0.07, 12.41]} rotation={[-3.14, 0.92, 3.04]} scale={3.02} />
      <mesh geometry={nodes.tree_027.geometry} material={nodes.tree_027.material} position={[-21.74, 1.69, 20.43]} rotation={[0, 1.41, 0]} scale={[1.76, 1.97, 2.42]} />
      <mesh geometry={nodes.tree_028.geometry} material={nodes.tree_028.material} position={[-26.2, 1.69, 20.43]} rotation={[0, 1.41, 0]} scale={[1.76, 1.97, 2.42]} />
      <mesh geometry={nodes.tree_029.geometry} material={nodes.tree_029.material} position={[-5.47, -0.44, 17.23]} rotation={[0, 1.41, 0]} scale={[1.76, 1.97, 2.42]} />
      <mesh geometry={nodes.tree_030.geometry} material={nodes.tree_030.material} position={[-9.01, -0.44, 17.23]} rotation={[0, 1.41, 0]} scale={[1.76, 1.97, 2.42]} />
      <mesh geometry={nodes.tree_032.geometry} material={nodes.tree_032.material} position={[-18.11, 2.23, 40.47]} rotation={[0, -0.59, 0]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_033.geometry} material={nodes.tree_033.material} position={[10.81, 2.85, 35.82]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_034.geometry} material={nodes.tree_034.material} position={[-27.03, 1.22, 30.37]} rotation={[-3.14, -1.08, 3.04]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_035.geometry} material={nodes.tree_035.material} position={[0.26, 0.07, 24.38]} rotation={[-3.14, 0.92, 3.04]} scale={3.02} />
      <mesh geometry={nodes.tree_037.geometry} material={nodes.tree_037.material} position={[4.99, 2.9, 19.02]} rotation={[-0.01, 1.41, -0.09]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_038.geometry} material={nodes.tree_038.material} position={[18.44, -0.44, 17.23]} rotation={[0, 1.41, 0]} scale={[1.76, 1.97, 2.42]} />
      <mesh geometry={nodes.tree_042.geometry} material={nodes.tree_042.material} position={[-38.44, 4.6, 23.54]} rotation={[-3.14, 0.92, 3.04]} scale={3.02} />
      <mesh geometry={nodes.tree_043.geometry} material={nodes.tree_043.material} position={[-41.78, 3.07, 29.48]} rotation={[-0.01, 1.41, -0.09]} scale={[3.05, 2.71, 3.07]} />
      <mesh geometry={nodes.tree_046.geometry} material={nodes.tree_046.material} position={[20.48, 3.11, 11.63]} rotation={[-0.01, 1.41, -0.09]} scale={[2.22, 1.97, 2.24]} />
      <mesh geometry={nodes.tree_047.geometry} material={nodes.tree_047.material} position={[-35.78, 2.52, 35.98]} rotation={[Math.PI, -1.07, Math.PI]} scale={[2.22, 1.97, 2.24]} />
    </group>
  )
}

useGLTF.preload('./assets/Homepage-scene.gltf')
